### ISSUE TITLE
Can't launch creep3r with ruby 1.9.3

### ISSUE THREAD

**Issue by shadowzoom** [Hood3dRob1n/creep3r#2]
I have ubuntu and ruby 1.9.3p484 (2013-11-22 revision 43786) [i686-linux]
i make installation from /creep3r/installers/ubuntu_setup.sh 
and when i try run creep3r im getting:
./creep3r
/var/lib/gems/1.9.1/gems/rubypress-1.0.7/lib/rubypress/xml_rpc_retryable.rb:7:in `<module:XMLRPCRetryable>': uninitialized constant Net::ReadTimeout (NameError)
    from /var/lib/gems/1.9.1/gems/rubypress-1.0.7/lib/rubypress/xml_rpc_retryable.rb:2:in`module:Rubypress'
    from /var/lib/gems/1.9.1/gems/rubypress-1.0.7/lib/rubypress/xml_rpc_retryable.rb:1:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/rubypress-1.0.7/lib/rubypress/client.rb:11:in`require_relative'
    from /var/lib/gems/1.9.1/gems/rubypress-1.0.7/lib/rubypress/client.rb:11:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/rubypress-1.0.7/lib/rubypress.rb:4:in`<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in`rescue in require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from ./creep3r:44:in`<main>'

I have installed latest version of rubypress. Same error with ruby 2.1.1:
./creep3r
/home/root1/Desktop/creep3r/classes/ruby-smbhash/lib/samba/encrypt.rb:49:in `<module:Private>': NotImplementedError (NotImplementedError)
    from /home/root1/Desktop/creep3r/classes/ruby-smbhash/lib/samba/encrypt.rb:37:in`module:Encrypt'
    from /home/root1/Desktop/creep3r/classes/ruby-smbhash/lib/samba/encrypt.rb:4:in `<module:Samba>'
    from /home/root1/Desktop/creep3r/classes/ruby-smbhash/lib/samba/encrypt.rb:3:in`<top (required)>'
    from /home/root1/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/root1/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from ./creep3r:65:in `<main>' 

Help me please, what packages i need install and what versions of ruby?

**Comment by Mattlanuze** [comment]
I am getting the same error, just seem to go around in circles  Any ideas?

**Comment by Hood3dRob1n** [comment]
Can you confirm you are running the latest copy available on Github? I updated a few days ago to address this issue with Rubypress as was reported by a few others as well. Project is targeted at Ruby 1.9 branch but working on rolling my own code for SMB hashing soon to try and remove this issue and version dependency.

**Comment by Mattlanuze** [comment]
I started by unknowingly using Ruby 1.7 and the latest version fron here. I've now uograded to katest Ruby too.

**Comment by Mattlanuze** [comment]
<CODE>/usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- anemone (LoadError)
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /home/mattlanuze/creep3r/creep3r:33:in `<main>'
</CODE>

**Comment by Hood3dRob1n** [comment]
Above error appears to indicate the Anemone gem was not installed and therefore can't be loaded. Did the installer file run and complete without errors? It should handle the system dependencies and then finish by running bundler which should install all of the rubygem dependencies. The command system command 'sudo gem install anemone' would normally do the trick for this one in particular (if installer seems to work but still failing). Sorry for the troubles, please provide some more info when you can and hopefully we can get you up and running.

**Comment by nh32** [comment]
Hello! I'm installing creeper in Kali-linux 1.0.6 with ruby 1.9.3p194. All dependencies are  completely  installed.
I have the same problem as SafeFolder:
in the first execution prompted to install rubypress

```
         (/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load suchfile            -- rubypress (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
   from creep3r:44:in `<main>')
```

Once installed, the error is:

/var/lib/gems/1.9.1/gems/rubypress-1.0.7/lib/rubypress/xml_rpc_retryable.rb:7:in `<module:XMLRPCRetryable>': uninitialized constant Net::ReadTimeout (NameError)
    from /var/lib/gems/1.9.1/gems/rubypress-1.0.7/lib/rubypress/xml_rpc_retryable.rb:2:in`module:Rubypress'
    from /var/lib/gems/1.9.1/gems/rubypress-1.0.7/lib/rubypress/xml_rpc_retryable.rb:1:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/rubypress-1.0.7/lib/rubypress/client.rb:11:in`require_relative'
    from /var/lib/gems/1.9.1/gems/rubypress-1.0.7/lib/rubypress/client.rb:11:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/rubypress-1.0.7/lib/rubypress.rb:4:in`<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in`rescue in require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from creep3r:44:in`<main>'

**Comment by Hood3dRob1n** [comment]
OK, should be updated now. Looks like I missed a reference to the rubypress gem after I yanked all the actual code. Super sorry for the mix up, please let me know if things are working now.

**Comment by Mattlanuze** [comment]
./creep3r:32:in `require': no such file to load -- rubygems (LoadError)
    from ./creep3r:32

fresh install

**Comment by nh32** [comment]
Hood3dRob1n!! now works perfect. I love the work you're doing. Thank you very much ;-)

**Comment by shadowzoom** [comment]
Now all works, thaks bro!
